---
title: "Create_spotfiles"
output: html_document
date: "2024-03-21"
---

```{r}
library(dplyr)
library(semla)
library(tidyr)
library(tools)
library(magick)
```

## Directory paths

```{r}
DIR_ROOT <- "~/Desktop/sATAC/240321_MGI/Analysis/240312_Mouse_Embryo_E14"
DIR_DATA <- file.path(DIR_ROOT,"data")
```

```{r}
# set paths to raw data and metadata
dirs <- list.dirs(DIR_DATA, recursive = F, full.names = F)
```

# Create table 

```{r}
table <- list()
```


```{r}
# create a table containing paths to raw and meta data (i.e., output from cellranger + spatial info)
#i corresponds to the sample name
for(i in dirs){
   table[[i]] <- data.frame(
     spotfiles = Sys.glob(file.path(DIR_DATA, i, "*_alignment.csv")), 
     imgs=Sys.glob(file.path(DIR_DATA,i ,"*-Spot000001.jpg")))
}
```

```{r}
infoTable <- do.call("rbind", table) %>% as.data.frame() 
```

```{r}
image_info <- LoadImageInfo(infoTable$imgs)
```


```{r}
# Nayanika version
# make tissue position files from the tsv files
for(i in 1:length(dirs)){
  spotfile <- read.table(infoTable$spotfiles[i], header = T)
  
  spotfile_tissue <- cbind(
    spotfile$row, #array_row
    spotfile$col, #array_col
    spotfile$x, #pxl_row_in_fullres
    spotfile$y #pxl_col_in_fullres
  ) %>% as.data.frame()
  tissue <- rep(i, nrow(spotfile_tissue))
  spotfile_tissue <- cbind(tissue, spotfile_tissue)
  rownames(spotfile_tissue) <- paste0(spotfile$barcode, "-1")
  
  # save new tissue position file with the correct columns for creating STutility object
  write.csv(spotfile_tissue, 
            paste0(strsplit(infoTable$tissue_paths[i],"tsv"), ".csv"))
  
}
```

```{r}
# Lovisa version
# make tissue position files from the tsv files
for(i in c(1,1)){
  s <- rownames(infoTable)[i]
  spotfile <- read.csv(infoTable$spotfiles[i], header = T)
  
  # spotfile_tissue <- cbind
  #   spotfile$row, #array_row
  #   spotfile$col, #array_col
  #   spotfile$x, #pxl_row_in_fullres
  #   spotfile$y #pxl_col_in_fullres
  # ) %>% as.data.frame()
  # tissue <- rep(i, nrow(spotfile_tissue))
  # spotfile_tissue <- cbind(tissue, spotfile_tissue)
  # rownames(spotfile_tissue) <- paste0(spotfile$barcode, "-1")
  
  # spotfile <- spotfile |> select(X, tissue, col, row, x, y)
  colnames(spotfile) <- c("barcode", "selected", "y", "x", "pxl_row_in_fullres", "pxl_col_in_fullres")
  
  # save new tissue position file with the correct columns for creating STutility object
  write.csv(spotfile, 
            file = file.path(DIR_DATA, s, 
                             paste0("tissue_positions_new", i, ".csv")), 
            row.names = F)
  
}
```



```{r}
# Load data from the csv file
for(i in seq_along(dirs)){
   # Read *_tissue.csv file
  xy.raw <- setNames(read.csv(file = infoTable$spotfiles[i]), 
                     nm = c("barcode", "selected", "y", "x", "pxl_row_in_fullres", "pxl_col_in_fullres"))  # nm = c("barcode", "tissue", "y", "x", "pixel_y", "pixel_x"))
  xy <- xy.raw[, c("x", "y")]
  
  img_path <- infoTable$imgs[i]
  img <- magick::image_read(img_path) 
  
  sf <- c(ncol(img)/128, nrow(img)/78)
  xy$x <- xy$x*sf[1]
  xy$y <- xy$y*sf[2]
  
  # Create a new spot selection table with proper image pixel coordinates which match the cropped images
  spotfile <- data.frame(xy.raw$barcode, xy.raw$tissue, xy.raw$y, xy.raw$x, round(xy$y), round(xy$x))
  write.table(spotfile, file = paste0(strsplit(infoTable$spotfiles[i], ".csv"), "_positions_list.csv"), 
              sep = ",", quote = F, row.names = F, col.names = F)
}
```


# Resize images
```{r}
scaleFactors <- numeric(nrow(infoTable))
```


```{r}
for(i in length(dirs)){
  #Read images from the image paths
  img_path <- infoTable$imgs[i]
  
  img <- image_read(img_path)
  
  #Record the original dimensions
  orig_width <- as.numeric(image_info(img)$width)
  orig_height <- as.numeric(image_info(img)$height)
  
  
  scale_factor <- min(2000 / orig_width, 2000 / orig_height)
  scaleFactors[i] <- scale_factor
  
  #Resize image to 2000px (This is the size of the image "hires" image obtained from spaceranger)
  
  if(scale_factor < 1) {
    resized_img <- image_resize(img, paste0("2000x2000"))
    output_file_path <- sub("\\.jpg$", "_hires.jpg", img_path)
    image_write(resized_img, output_file_path)
  } else {
    cat("Image is already smaller than or equal to 2000 pixels on both sides:", img_path, "\n")
  }
}
  

# Append scale factor to the infoTable
infoTable$scaleFactor <- scaleFactors

#Save the infoTable to be able to access the scalefactors later
# write.csv(infoTable, "infoTable_with_scaleFactors.csv", row.names = FALSE)
```


